---
version: '3'
services:
  steve-events-api:
    image: steve-events-api:latest
    container_name: steve-events-api
    build:
      context: ./
      dockerfile: ./Dockerfile
    environment:
      SERVER_PORT: "8088"
      GOOGLE_HOST: https://content.googleapis.com
      AUTH_URL: 'http://steve-auth-api:8080'
      MONGO_URI: mongodb://mongo:27017
      MONGO_USER: root
      MONGO_PASSWORD: root
      MONGO_DATABASE: calendar
      MONGO_COLLECTION: events
    ports:
      - 8088:8088
  mongo:
    image: mongo:4.2.3
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: "root"
      MONGO_INITDB_ROOT_PASSWORD: "root"

    ports:
      - 27017:27017
